spring:
  application:
    name: rest-with-spring-boot-and-java-erudio

  # DATA SOURCE -> POSTGRES
  datasource:
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  # JPA/HIBERNATE
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false

#logging:
#  level:
#    root: WARN
#    br.com.erudio: DEBUG